# Site settings
title: Mats Esseldeurs
email: mats.esseldeurs@kuleuven.be
description: Academic webpage of Mats Esseldeurs
baseurl: ""
url: "https://MatsEsseldeurs.github.io"

# Google analytics ID: Uncomment and your own, if you like
google_analytics_4: G-PEJNCDJHLV
google_search_console: cCnvBw3B25-aYTQkN247kUWhsP884LMFu2ge4UXqiq0
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Mats Esseldeurs<br/>
    PhD in Astronomy<br/>
    Institute of Astronomy,<br/>
    KU Leuven

location: >
  Institute of Astronomy,<br/> KU Leuven<br/>
  Celestijnenlaan 200d - 03.38<br/>
  3001 Heverlee, Belgium

contact: >
    <a href="mailto:mats.esseldeurs@kuleuven.be" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Mats via email</a> <br/>
    <a href="https://github.com/MatsEsseldeurs/academic-website-template"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: Publications
  - name: Talks
  - name: Research
  - name: Software
  - name: CV

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:

  last_name: Esseldeurs
  first_name: [Mats, M.]

  style: citesty
  locale: en

  source: /_bibliography/
  bibliography: articles.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending
  bibliography_list_tag: ul
  # bibliography_item_tag: il

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  bibtex_skip_fields: [abstract, month_numeric, file, link, status, slides, poster, poster_pres, invited, selected, addit, winds, tides, firstauthor]

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
