# Site settings
title: Daniel Borin
email: daniel.borin[at]unesp.br
description: Academic webpage of Daniel Borin
baseurl: ""
url: "https://danielborin.github.io"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics_4: G-PEJNCDJHLV
# google_search_console: cCnvBw3B25-aYTQkN247kUWhsP884LMFu2ge4UXqiq0
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Daniel Borin<br/>

location: >
  São Paulo State University (UNESP)<br/>
  Institute of Geosciences and Exact Sciences, Department of Physics,
  13506-900, Rio Claro, SP, Brazil

contact: >
    You can reach me at:<br><a href="mailto:daniel.borin[at]unesp.br" target="_blank"><i class="fa fa-envelope fa-1x"></i> daniel.borin[at]unesp.br</a>

location_ptbr: >
    Universidade Estadual Paulista (UNESP)<br/>
    Instituto de Geociências e Ciências Exatas, Departamento de Física,
    CEP: 13506-900, Rio Claro, SP, Brasil

contact_ptbr: >
    Você pode entrar em contato comigo em:<br><a href="mailto:daniel.borin[at]unesp.br" target="_blank"><i class="fa fa-envelope fa-1x"></i> daniel.borin[at]unesp.br</a>

# Pages shown in navbar
nav_pages:
  # - name: About
  - name: Publications
  - name: Teaching
  # - name: Research
  # - name: Software
  # - name: CV

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll/scholar

scholar:

  last_name: Borin
  first_name: [Borin, D.]

  style: citesty
  locale: en

  source: /papers/
  bibliography: articles.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending
  bibliography_list_tag: ul
  # bibliography_item_tag: il

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  bibtex_skip_fields: [abstract, month_numeric, file, link, status, slides, poster, poster_pres, invited, selected, addit, winds, tides, firstauthor]

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
